### PR TITLE
Deserialization

### PR DESCRIPTION
**Pull request by FranciscoThiesen**
- Adding a simple json parser
- Adding from_json file that uses reflection capabilities to build arbitrary types from JsonValue.
- Adding example2.cpp that shows the serialization + deserialization. (Pattern that is good when coming up with new tests)

Please keep in mind that this is just an initial parser version. We have a lot of ideas to drawn from the official simdjson repo if we decide that we want to have a fast parser + deserializer in this repo!

@lemire please take a look

### CODE REVIEW

**Comment by lemire** [comment]
@FranciscoThiesen I wonder whether the examples should not go in a distinct repository? I don't think matters very much, but it would be a bit cleaner if there were separate.

**Review by lemire — APPROVED** [review]

**Comment by FranciscoThiesen** [comment]
@lemire by the examples you also mean to separate the deserializer from this repo, or just the example files?

**Comment by lemire** [comment]
> by the examples you also mean to separate the deserializer from this repo, or just the example files?

Let me more precise. I had in mind that we could create a new directory called 'examples' that would get built just like the benchmarks, as a separate component.

Your PR is fine and what I am proposing could be done later.

**Comment by FranciscoThiesen** [comment]
Ok! Will merge then refactor into a separate directory.

**Pull request merged**
